dependencies {
    implementation project(":messages")
    implementation project(":serialize-java")
    implementation project(":serialize-proto")
    implementation project(":serialize-test-fixtures")

    // Source: https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation("com.fasterxml.jackson.core:jackson-databind:2.21.0")

    // JMH
    testImplementation 'org.openjdk.jmh:jmh-core:1.37'
    testImplementation 'org.openjdk.jmh:jmh-generator-annprocess:1.37'
}

jmh {
    fork = 1
    warmupIterations = 5
    warmup = '1s'
    iterations = 10
    timeOnIteration = '1s'
    benchmarkMode = ['avgt']
    timeUnit = 'ns'
    resultFormat = 'JSON'
    resultsFile = file("$buildDir/jmh/results.json")
}

tasks.register('analyzeMsgSizesJava', JavaExec) {
    group = "analysis"
    description = "Serializes message and writes size to file"

    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'bftsmart.analysis.MemoryAnalysis'

    def outputFile = layout.buildDirectory.file("metrics/message-size.json")
    args outputFile.get().asFile.absolutePath

    outputs.file(outputFile)
}

tasks.register('analyzeMsgSizes', Exec) {
    dependsOn ':analysis:analyzeMsgSizesJava'
    commandLine 'python3', "$projectDir/plot_memory.py",
            "$buildDir/metrics/message-size.json"
}

tasks.register('analyzeJmh', Exec) {
    dependsOn ':analysis:jmh'
    commandLine 'python3', "$projectDir/plot_jmh.py", "$projectDir/build/jmh/results.json"
}

tasks.register('analyze') {
    group = 'analysis'
    description = 'Runs message size and JMH analysis'

    dependsOn 'analyzeMsgSizes', 'analyzeJmh'
}
